// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFolder() {
  return window['go']['main']['App']['GetFolder']();
}

export function GetLang() {
  return window['go']['main']['App']['GetLang']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function Translate(arg1) {
  return window['go']['main']['App']['Translate'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
