// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function GetFolder():Promise<string>;

export function GetLang():Promise<string>;

export function GetSettings():Promise<settings.AppSettings>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function Translate(arg1:string):Promise<string>;

export function UpdateSettings(arg1:settings.AppSettings):Promise<void>;
